import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { getFreeFonts } from "@/utils/getFonts";
import Head from "next/head";

const bebasMono = localFont({
  src: "./fonts/JosefinSans-VariableFont_wght.ttf",
  variable: "--font-bebas",
  weight: "100 200 300 400 500 600 700",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const generateFontLink = () => {
  const fontsLink = getFreeFonts().map((font) => {
    const styleLinks = font.fontStyle
      .split(" ")
      .map(
        (style) =>
          `https://raw.githubusercontent.com/Digit-House/MMFonts-Client/develop/public/fonts/${font.fileName}/${style}.ttf`,
      );
    return styleLinks.join("\n");
  });
  return fontsLink;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {generateFontLink().map((link) => (
          <link
            rel="preload"
            href={link}
            as="font"
            crossOrigin="anonymous"
            key={link}
          />
        ))}
      </Head>
      <body
        className={`${bebasMono.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
